# Generated by Django 5.1 on 2024-10-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sistema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(max_length=1024),
        ),
    ]
