# Generated by Django 5.1.2 on 2024-11-26 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_cronograma_evento_alter_participante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='Sistema.evento'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='Nome_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participante_externo',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participanteEX', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
