# Generated by Django 5.1 on 2024-12-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sistema", "0004_alter_cronograma_evento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessao",
            name="cronograma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessoes",
                to="Sistema.cronograma",
            ),
        ),
    ]
